set-option -g default-shell /bin/zsh
set-option -g default-terminal "xterm-256color"
set -g base-index 1
set -g renumber-windows on
set -g mode-keys vi
set -g window-status-current-style "fg=black bg=white"
set -g status-style "bg=default"

# vim-like pane switching
bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R 

# lets us not need to release ctrl for next and prev window
bind C-p previous-window
bind C-n next-window

bind E show-environment -g

unbind C-Up
unbind C-Down
unbind C-Left
unbind C-Right

