set-option -g default-shell /bin/zsh
set-option -g default-terminal "xterm-256color"
set -g base-index 1
set -g renumber-windows on
set -g set-clipboard on
set -g allow-passthrough on
set -g mode-keys vi
set -g window-status-current-style "fg=black bg=white"
set -g status-style "bg=default"

# vim-like pane switching
bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R 

# lets us not need to release ctrl for next and prev window
bind C-p previous-window
bind C-n next-window

bind E show-environment -g

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/plugins/'
run '~/.tmux/plugins/tpm/tpm'
